version: '3.7'
services:
  resume-discovery-service:
    image: thisisalexis/resume-discovery-service:1.0.0
    container_name: resume-discovery-service
    hostname: resume-discovery-service
    ports:
      - 8761:8761
    working_dir: /opt/app
    networks:
      - shared-net
  resume-skills-app:
    image: thisisalexis/resume-skills-app:1.0.0
    container_name: resume-skills-app
    ports:
      - 8090:8080
    working_dir: /opt/app
    depends_on:
      - resume-skills-mongo-db
      - resume-discovery-service
    links:
      - resume-skills-mongo-db
      - resume-discovery-service
    networks:
      - shared-net
  resume-skills-mongo-db:
    image: mongo
    container_name: resume-skills-mongo-db
    ports:  # for demo/debug purpose only
      - 27017:27017
    volumes:
      - $HOME/data/resume-skills-mongo-db-data:/data/db
      - $HOME/data/resume-skills-mongo-db-bkp:/data/bkp
    restart: always
    networks:
      - shared-net
networks:
  shared-net:
    driver: bridge